### ISSUE TITLE
voidvault crashes asking for root priviledges

### ISSUE THREAD

**Issue by mobinmob** [atweiden/voidvault#1]
voidvault version: 1.5.2
voidlinux iso: void-live-x86_64-20181111-mate.iso (official)

I booted the live system adding _rd.live.overlay.overlayfs=1_ to the kernel command line to have more space available, installed the necessary dependencies and started the installation with voidvault new. The program crashed immediately after the timezone selection with the following error:

`root privileges required
  in method bootstrap at 
/home/anon/voidvault-1.5.2/lib/Voidvault/Bootstrap.pm6 
(Voidvault::Bootstrap) line 25
  in method new at /home/anon/voidvault-1.5.2/lib/Voidvault.pm6 
(Voidvault) line 46
  in sub MAIN at /home/anon/voidvault-1.5.2/bin/voidvault line 128
  in block <unit> at /home/anon/voidvault-1.5.2/bin/voidvault line 259`

It is obvious that an installer needs to run as root, but running as a user up to a point and then crashing is... confusing :)

**Comment by atweiden** [comment]
Will likely solve by clarifying the instructions.

**Comment by mobinmob** [comment]
You can also check and abort with an error message if the UID is not 0.
