### ISSUE TITLE
Kde connect is not connecting

### ISSUE THREAD

**Issue by Pixxler** [atweiden/voidvault#12]
Hello, I have recently installed void with voidvault.
The problem is I cannot connect with my android phone. Looks like something is blocking. I am not a technical person. I have tried to solve the problem but I cant. Please help me regarding this issue. I need kde connect working for day to day work. Much appreciated for this amazing project. Thank you. 🙏

sorry, my english is not good.

**Comment by atweiden** [comment]
I’m sorry, but this issue tracker isn’t an appropriate forum for KDE Connect tech support. I don’t have any experience using KDE Connect, and I don’t intend to acquire any KDE Connect expertise at this time.

Frankly, I’d advise installing Manjaro.
