### ISSUE TITLE
Unable to install on nvme.

### ISSUE THREAD

**Issue by mobinmob** [atweiden/voidvault#5]
iso image: latest unofficial voidiso (2018.11.18)
voidvault version: gh master 
Installation on virtualbox (6.0.4) with with extension pack το enable virtual nvme controller.

Installation proceeds as it is supposed to until  mkfs.vfat tries to format the ESP:
https://imgur.com/a/fZpcPQg
I am pretty sure that the problem is that voidvault does not expect the differences in nvme device names: /dev/nvme0n12 cannot be a partition, the partitions are nvme0n1p1, nvme0n1p2 etc.
The partitioning itself is ok:
https://imgur.com/a/HKBQ4bd

**Comment by atweiden** [comment]
is this possible to replicate in vbox without having nvme hardware?

what is the output of `voidvault ls partitions`?

**Comment by atweiden** [comment]
On NVMe drives, `$config.partition` becomes `/dev/nvme0n1`. However, Voidvault currently has no way of knowing it needs to prepend `p` to the partition numbers it produces when deriving targets. It should be 

`nvme0n1p2` not 
`nvme0n12`

SSDs and HDDs work differently.

I'm thinking a new `NVME` disk type needs to be added. I'll look into this.

**Comment by atweiden** [comment]
@mobinmob can you test the nvme branch to see if it fixes #5?

**Comment by mobinmob** [comment]
Voidvault finishes installation without problems in both bios/legacy boot and efi on vbox. It cannot boot after the installation when installed in bios mode (efi is fine) :(
Vbox error message is :
`FATAL: Could not read from the boot medium! System halted.`
I used the same disk image in both scenarios and tried twice in bios mode with the same result.

**Comment by atweiden** [comment]
could it be the case your NVMe disk [requires UEFI](https://www.intel.com/content/www/us/en/support/articles/000005967/memory-and-storage/enthusiast-ssds.html)?

> Using an NVMe device to boot a computer system requires:
>
> - System BIOS configured to enable UEFI* version 2.3.1 and support NVMe boot
> - System based on an Intel® Z97 or X99 Chipset
> - 64-bit operating system that supports UEFI; Windows 7*, 8*, 8.1* or Windows® 10
> - Setting the CSM in the system BIOS (for Windows 7)
> - Intel® NVMe driver

**Comment by mobinmob** [comment]
That is indeed the case with [virtualbox nvme support](https://www.virtualbox.org/manual/ch05.html) :

> Warning
>Booting from drives attached using NVMe is only supported when EFI is used as the BIOS lacks the appropriate driver. 

It didn' t cross my mind :)
